create extension if not exists pgcrypto;

alter table public.audit_log
  add column if not exists sequence_number bigint generated by default as identity,
  add column if not exists previous_hash text,
  add column if not exists event_hash text,
  add column if not exists hash_algorithm text not null default 'sha256';

create unique index if not exists audit_log_sequence_number_key
on public.audit_log(sequence_number);

create or replace function public.set_audit_log_hash()
returns trigger
language plpgsql
as $$
declare
  last_hash text;
begin
  select event_hash
  into last_hash
  from public.audit_log
  where sequence_number < new.sequence_number
  order by sequence_number desc
  limit 1;

  new.previous_hash := coalesce(last_hash, 'APP-PRV-004-GENESIS');
  new.hash_algorithm := 'sha256';
  new.event_hash := encode(
    digest(
      concat_ws(
        '|',
        new.sequence_number::text,
        coalesce(new.actor_id::text, ''),
        new.table_name,
        coalesce(new.record_id::text, ''),
        new.action,
        new.pii_action::text,
        coalesce(new.performed_by::text, ''),
        new.performed_at::text,
        new.previous_hash,
        new.metadata::text
      ),
      'sha256'
    ),
    'hex'
  );

  return new;
end;
$$;

drop trigger if exists audit_log_hash_chain on public.audit_log;
create trigger audit_log_hash_chain
before insert on public.audit_log
for each row execute function public.set_audit_log_hash();
